server:
  port: 8081
spring:
  application:
    name: "CARDS"
  datasource:
    url: jdbc:mysql://localhost:3306/bank-app-microservices
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "qa"


management:
  endpoints:
    web:
      exposure:
        include: "*"  # tüm endpointleri açık hale getirir
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
info:
  app:
    name: "Cards Microservice"
    description: "Project for Spring Boot Microservices Course"
    version: "1.0.0"
