server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 12345
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

build:
  version: "1.0"

# prefix ile başlayan tüm endpointlerin bu prefix ile başlamasını sağlar
accounts:
  message: "Welcome to Accounts API"
  contactDetails:
    name: "John Doe - Developer"
    email: "orhantrkmn749@gmail.com"
  onCallSupport:
    - "(555) 555-5555"
    - "(555) 555-5556"
