version: '3.8'

services:
  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices_network

  # Gateway Server Service
  gateway-server:
    image: orhanturkmenoglu/gateway-server:s3
    container_name: gateway-server
    build:
      context: ./gateway-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - loans
      - cards
      - accounts
    networks:
      - microservices_network

  # Loans Service
  loans:
    image: orhanturkmenoglu/loans:s3
    container_name: loans
    build:
      context: ./loans
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/loansdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - microservices_network

  # Cards Service
  cards:
    image: orhanturkmenoglu/cards:s3
    container_name: cards
    build:
      context: ./cards
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cardsdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    networks:
      - microservices_network

  # Accounts Service
  accounts:
    image: orhanturkmenoglu/accounts:s3
    container_name: accounts
    build:
      context: ./accounts
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/accountsdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    networks:
      - microservices_network

  # MySQL Database for Loans, Cards, and Accounts Services
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=loansdb
      - MYSQL_DATABASE=cardsdb
      - MYSQL_DATABASE=accountsdb
    ports:
      - "3306:3306"
    networks:
      - microservices_network

  # Config Server (Optional, if you have centralized configuration)
  config-server:
    image: orhanturkmenoglu/config-server:s3
    container_name: config-server
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - redis
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge
