server:
  port: 8761

spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false      # Bu ayar  kayıt defterine kayıt olup olmayacağını belirtir.
    register-with-eureka: false  # Bu ayar eureka kayıt defterine kayıt olup olmayacağını belirtir.
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/