build:
  version: "1.0"

# prefix ile başlayan tüm endpointlerin bu prefix ile başlamasını sağlar
accounts:
  message: "Welcome to Accounts API"
  contactDetails:
    name: "John Doe - Developer"
    email: "orhantrkmn749@gmail.com"
  onCallSupport:
    - "(555) 555-5555"
    - "(555) 555-5556"
