build:
  version: "3.0"

# prefix ile başlayan tüm endpointlerin bu prefix ile başlamasını sağlar
cards:
  message: "Welcome to Loans  API - DEFAULT"
  contactDetails:
    name: "John Doe - Default Owner"
    email: "orhantrkmn749@gmail.com"
  onCallSupport:
    - "(333) 555-5555"
    - "(333) 555-5556"

