build:
  version: "1.0"

# prefix ile başlayan tüm endpointlerin bu prefix ile başlamasını sağlar
cards:
  message: "Welcome to Loans  API - QA"
  contactDetails:
    name: "John Doe - QA Owner"
    email: "orhantrkmn749@gmail.com"
  onCallSupport:
    - "(333) 555-5555"
    - "(333) 555-5556"
